### ISSUE TITLE
Feature: multiple labels

### ISSUE THREAD

**Issue by volgin** [faob-dev/flutter_circular_text#2]
Great plugin!

It would be awesome to be able to set multiple text labels, each with its own position property (e.g. start angle OR end angle OR center angle).

Alternatively, or in addition, multiple labels can be rendered using spacing property (start, end, space around, space evenly) - similar to columns / rows. Also, similar to other Flutter widgets this widget can have ‘children’ property for multiple text labels.

**Comment by faob-dev** [comment]
Hi i added multi text and `StartAngleAlignment` property

With 
`StartAngleAlignment.start` text will starts from `startAngle` 
`StartAngleAlignment.center` text will be centered on `startAngle`  
`StartAngleAlignment.end`  text will ends on `startAngle`

Please see video demo here `startAngle = 0` and i changed `StartAngleAlignment` property 
https://youtu.be/_gjOuFTpLts

Is this what you wanted in first part?

**Comment by volgin** [comment]
Very impressive! Thank you!
